const About = () => {
    
    return (

        <div className="p-8">

            <Head>
                <title>Illustrator</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                <link rel="icon" href="/logo.svg" />
            </Head>

        </div>

    );

}


export default About;