import Head from "next/head";
import Link from "next/link";
import Hero from "../components/hero";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { Fragment, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";


const Home = () => {

    const [selectedId, setSelectedId] = useState(null);

    const minimal = [
        {uri: "https://markrise.art/wp-content/uploads/2022/01/800.jpg", id: 1},
        {uri: "https://markrise.art/wp-content/uploads/2021/12/800-4.jpg", id: 2},
        {uri: "https://markrise.art/wp-content/uploads/2022/02/800.jpg", id: 3},
        {uri: "https://markrise.art/wp-content/uploads/2021/11/800-3.jpg", id: 4},
        {uri: "https://markrise.art/wp-content/uploads/2021/11/64cover.jpg", id: 5},
        {uri: "https://markrise.art/wp-content/uploads/2021/09/1600-1.jpg", id: 6},
        {uri: "https://markrise.art/wp-content/uploads/2021/08/Day-57.jpg", id: 7},
        {uri: "https://markrise.art/wp-content/uploads/2021/04/day-9-1.jpg", id: 8}
    ];

    const abstract = [
        { uri: "https://markrise.art/wp-content/uploads/2021/11/800-2.jpg", id: 29 },
        { uri: "https://markrise.art/wp-content/uploads/2022/02/800-5.jpg", id: 9 },
        { uri: "https://markrise.art/wp-content/uploads/2022/01/800-5.jpg", id: 10 },
        { uri: "https://markrise.art/wp-content/uploads/2021/12/800-3.jpg", id: 11 },
        { uri: "https://markrise.art/wp-content/uploads/2022/02/800-4.jpg", id: 12 },
        { uri: "https://markrise.art/wp-content/uploads/2022/01/800-1.jpg", id: 13 },
        { uri: "https://markrise.art/wp-content/uploads/2022/01/800-3.jpg", id: 14 },
        { uri: "https://markrise.art/wp-content/uploads/2022/02/800-6.jpg", id: 15 }
    ];

    const nfts = [
        { uri: "https://markrise.art/wp-content/uploads/2022/06/6-Fishman.jpg", id: 100 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/8-Spaceman.jpg", id: 102 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/14-DJ.jpg", id: 103 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/17-Jungleman.jpg", id: 104 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/18-Birdman.jpg", id: 105 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/19-Peacemake.jpg", id: 106 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/21-Bridge.jpg", id: 107 },
        { uri: "https://markrise.art/wp-content/uploads/2022/06/24-Memories.jpg", id: 108 }
    ];


    return (

        <Fragment>

            <div className="p-8">

                <Head>
                    <title>Illustrator</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                    <link rel="icon" href="/logo.svg" />
                </Head>

                <Navbar />

                <Hero />

                <div className="my-24">

                    <h2 className="font-medium text-center text-2xl text-slate-900">If you want to shine, find the brightest star in your mind.</h2>

                </div>

                <div className="p-10 bg-black rounded-md text-center">

                    <h2 className="font-light text-7xl text-amber-400 mb-6">Minimal Illustrations</h2>

                    <p className="font-medium text-base text-white mb-8">FLAT DESIGN STYLE</p>

                    <Link href="/minimal-illustrations">
                        <a className="py-3 px-6 rounded-md font-medium text-slate-900 bg-amber-400">View All</a>
                    </Link>

                </div>

                <div className="my-24 grid grid-cols-4 gap-6">

                    {minimal.map(item => (
                        <motion.img loading="lazy" className="rounded-md cursor-pointer" alt="illustration" key={item.id} src={item.uri} layoutId={item.id} onClick={() => setSelectedId({ id: item.id, uri: item.uri })} />
                    ))}

                </div>

                <div className="mb-24">

                    <h2 className="font-medium text-center text-2xl text-slate-900">Art is like a game. There is always the next level.</h2>

                </div>

                <div className="p-10 bg-amber-400 rounded-md text-center">

                    <h2 className="font-light text-7xl text-slate-900 mb-6">Abstract Illustrations</h2>

                    <p className="font-medium text-base text-white mb-8">SIMPLE GEOMETRIC FORMS</p>

                    <Link href="abstract-illustrations">
                        <a className="py-3 px-6 rounded-md font-medium text-white bg-slate-900">View All</a>
                    </Link>

                </div>

                <div className="my-24 grid grid-cols-4 gap-6">

                    {abstract.map(item => (
                        <motion.img loading="lazy" className="rounded-md cursor-pointer" alt="illustration" key={item.id} src={item.uri} layoutId={item.id} onClick={() => setSelectedId({ id: item.id, uri: item.uri })} />
                    ))}

                </div>

                <div className="mb-24">

                    <h2 className="font-medium text-center text-2xl text-slate-900">The artist is a bridge between heaven and earth.</h2>

                </div>

                <div className="p-10 bg-black rounded-md text-center">

                    <h2 className="font-light text-7xl text-amber-400 mb-6">NFT Collection</h2>

                    <p className="font-medium text-base text-white mb-8">THE FACES OF GOD</p>

                    <Link href="/nft">
                        <a className="py-3 px-6 rounded-md font-medium text-slate-900 bg-amber-400">View All</a>
                    </Link>

                </div>

                <div className="my-24 grid grid-cols-4 gap-6">

                    {nfts.map(item => (
                        <motion.img loading="lazy" className="rounded-md cursor-pointer" alt="illustration" key={item.id} src={item.uri} layoutId={item.id} onClick={() => setSelectedId({ id: item.id, uri: item.uri })} />
                    ))}

                </div>

                <Footer />

            </div>

            <AnimatePresence>
                {selectedId && (
                    <motion.div onClick={() => setSelectedId(null)} className="flex items-center justify-center fixed left-0 top-0 w-full h-full bg-slate-900/90" layoutId={selectedId}>
                        <motion.img className="rounded-md w-4/12" src={selectedId.uri} layoutId={selectedId.id} />
                    </motion.div>
                )}
            </AnimatePresence>

        </Fragment>

    );

}


export default Home;