import Head from "next/head";
import About from "../components/about";
import Hero from "../components/hero";


const Home = () => {

    return (

        <div className="p-8">

            <Head>
                <title>Illustrator</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero />

            <About />

        </div>

    );

}


export default Home;