import Head from "next/head";
import Link from "next/link";
import Hero from "../components/hero";
import Navbar from "../components/navbar";


const Home = () => {

    return (

        <div className="p-8">

            <Head>
                <title>Illustrator</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <Hero />

            <div className="my-24">

                <h2 className="font-medium text-center text-2xl text-slate-900">If you want to shine, find the brightest star in your mind.</h2>

            </div>

            <div className="p-10 bg-black rounded-md text-center">

                <h2 className="font-light text-7xl text-amber-400 mb-6">Minimal Illustrations</h2>

                <p className="font-medium text-base text-white mb-8">FLAT DESIGN STYLE</p>

                <Link href="/minimal-illustrations">
                    <a className="py-3 px-6 rounded-md font-medium text-slate-900 bg-amber-400">View All</a>
                </Link>

            </div>

            <div className="my-24 grid grid-cols-4 gap-6">

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/08/Day-55.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/01/800.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/12/800-4.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/02/800.jpg" alt="illustration" />

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/11/800-3.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/11/64cover.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/09/1600-1.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/08/Day-57.jpg" alt="illustration" />
                
            </div>

            <div className="mb-24">

                <h2 className="font-medium text-center text-2xl text-slate-900">Art is like a game. There is always the next level.</h2>

            </div>

            <div className="p-10 bg-gradient-to-r from-amber-500 to-amber-300 rounded-md text-center">

                <h2 className="font-light text-7xl text-slate-900 mb-6">Abstract Illustrations</h2>

                <p className="font-medium text-base text-white mb-8">SIMPLE GEOMETRIC FORMS</p>

                <Link href="abstract-illustrations">
                    <a className="py-3 px-6 rounded-md font-medium text-white bg-slate-900">View All</a>
                </Link>

            </div>

            <div className="my-24 grid grid-cols-4 gap-6">

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/11/800-2.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/02/800-6.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2021/12/800-3.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/01/800-1.jpg" alt="illustration" />

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/02/800-4.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/02/800-5.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/01/800-5.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/01/800-3.jpg" alt="illustration" />
                
            </div>

            <div className="mb-24">

                <h2 className="font-medium text-center text-2xl text-slate-900">The artist is a bridge between heaven and earth.</h2>

            </div>

            <div className="p-10 bg-black rounded-md text-center">

                <h2 className="font-light text-7xl text-amber-400 mb-6">NFT Collection</h2>

                <p className="font-medium text-base text-white mb-8">THE FACES OF GOD</p>

                <a href="" className="py-3 px-6 rounded-md font-medium text-slate-900 bg-amber-400">View All</a>

            </div>

            <div className="my-24 grid grid-cols-4 gap-6">

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/6-Fishman.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/8-Spaceman.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/14-DJ.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/17-Jungleman.jpg" alt="illustration" />

                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/18-Birdman.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/19-Peacemake.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/21-Bridge.jpg" alt="illustration" />
                <img className="rounded-md" src="https://markrise.art/wp-content/uploads/2022/06/24-Memories.jpg" alt="illustration" />
                
            </div>

            <footer className="p-4 flex flex-row aling-center justify-center">

                <i class="fi fi-brands-instagram text-slate-900 text-lg"></i>
                <i class="fi fi-brands-youtube text-slate-900 text-lg"></i>
                <i class="fi fi-brands-twitter text-slate-900 text-lg"></i>
                <i class="fi fi-brands-dribbble text-slate-900 text-lg"></i>

            </footer>

        </div>

    );

}


export default Home;