import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import Gallery from "../components/nft/gallery";


const Nft = () => {

    return (

        <div className="p-8">

            <Head>
                <title>NFT - Mark Rise</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <div className="bg-cover-nft-illustrations h-screen rounded-t-md bg-fixed"></div>
            <div className="rounded-b-md p-4 bg-black">
                <p className="font-normal text-lg text-center text-amber-400 mb-2">The Faces of God</p>
                <p className="font-medium text-xs text-center text-white">NFT COLLECTION</p>
            </div>

            <Gallery />

            <Footer />

        </div>

    );

}


export default Nft;